using Serenity.Navigation;
using MyPages = DAP.DWSupport.Pages;

[assembly: NavigationMenu(int.MaxValue, "DW Support", icon: "fa-exchange")]
[assembly: NavigationLink(int.MaxValue, "DW Support/Financial Report Publishing", typeof(MyPages.FinReportPublishingSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/District Master", typeof(MyPages.DistrictMasterSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Guest Prevent Departure", typeof(MyPages.GuestPreventDepartureController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Survey Filter Exclusion", typeof(MyPages.SurveyFilterExclusionSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Strategic Price Control", typeof(MyPages.TblStrategicPriceControlController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Sailing Master", typeof(MyPages.SailingMasterSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Port Name Substitutions", typeof(MyPages.PortSubstitutionSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Invoice Item Type Master", typeof(MyPages.InvoiceItemTypeMasterSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Amenities", typeof(MyPages.AmenitiesSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Agency Snapshot Request", typeof(MyPages.AgencySnapshotRequestController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Casino Slot Master Desc Supp", typeof(MyPages.CasinoSlotMasterDescSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Category Master Supp", typeof(MyPages.CategoryMasterSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Currency Exchange Rate Supp", typeof(MyPages.CurrencyExchangeRateSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Full Ship Charters Supp", typeof(MyPages.FullShipChartersSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Minibar Setup Supp", typeof(MyPages.MinibarSetupSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Rollup Product Codes Supp", typeof(MyPages.RollupProductCodesSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/PS GL Account Supp", typeof(MyPages.PsGlAccountSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Fin Planned Capacity Supp", typeof(MyPages.FinPlannedCapacitySuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/CMI Supp", typeof(MyPages.CmiSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/GTF Supp", typeof(MyPages.GtfSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/PS GL Account Supp", typeof(MyPages.PsGlAccountSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Upgrade Adv Adj Supp", typeof(MyPages.UpgradeAdvAdjSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/Credit Card Adj Supp", typeof(MyPages.CreditCardAdjSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "DW Support/PS GL Account Supp", typeof(MyPages.PsGlAccountSuppController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Brand Finance & Strategy/Stly Dates", typeof(MyPages.StlyDatesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "DW Support/Amenity Details Supp", typeof(MyPages.AmenityDetailsSuppController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "DW Support/Import Error Log", typeof(MyPages.ImportErrorLogController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "DW Support/Invoice Item Type", typeof(MyPages.InvoiceItemTypeSuppController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "DW Support/Product Codes", typeof(MyPages.ProductCodeSuppController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "DW Support/Sailing Product Codes", typeof(MyPages.SlProductCodeSuppController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "DWSupport/Import Error Log", typeof(MyPages.ImportErrorLogController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "DW Support/Invoice Item Type", typeof(MyPages.InvoiceItemTypeSuppController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "DW Support/Product Codes", typeof(MyPages.ProductCodeSuppController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "DW Support/Sailing Product Codes", typeof(MyPages.SlProductCodeSuppController), icon: null)]